# Generated by Django 2.0 on 2018-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perexpense',
            name='cost',
            field=models.FloatField(),
        ),
    ]
