# Generated by Django 2.0 on 2018-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business',
            field=models.CharField(max_length=200),
        ),
    ]
