# Generated by Django 2.0 on 2018-03-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open_Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('complain_id', models.CharField(max_length=50)),
                ('com_type', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
