# Generated by Django 2.0 on 2018-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_support_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionm',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
