# Generated by Django 2.0 on 2018-02-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180216_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.FloatField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
