# Generated by Django 2.0 on 2018-02-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.FloatField(blank=True, max_length=7),
        ),
    ]
