# Generated by Django 2.0 on 2018-03-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180217_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='danger_level',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
