# Generated by Django 2.0 on 2018-03-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20180302_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpenseRecord',
        ),
    ]
