# Generated by Django 2.0 on 2018-02-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20180221_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranrecord',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
