# Generated by Django 2.0 on 2018-02-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20180221_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranrecord',
            name='profit',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
