# Generated by Django 2.0 on 2018-02-22 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_tranrecord_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranrecord',
            name='t_id',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tranrecord',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Invoice'),
        ),
    ]
