# Generated by Django 2.0 on 2018-02-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20180222_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranrecord',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
