# Generated by Django 2.0 on 2018-02-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20180222_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranrecord',
            name='t_id',
            field=models.CharField(max_length=200),
        ),
    ]
