# Generated by Django 2.0 on 2018-02-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20180222_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
