# Generated by Django 2.0 on 2018-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20180222_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsinvoice',
            old_name='item',
            new_name='name',
        ),
        migrations.AddField(
            model_name='accountsinvoice',
            name='buyer',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountsinvoice',
            name='t_id',
            field=models.CharField(default='123fsdd', max_length=200),
            preserve_default=False,
        ),
    ]
