# Generated by Django 2.0 on 2018-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_accountsinvoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='profit',
            field=models.FloatField(default=250.0),
            preserve_default=False,
        ),
    ]
