# Generated by Django 2.0 on 2018-03-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_tranrecord_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranrecord',
            name='t_id',
        ),
    ]
