# Generated by Django 2.0 on 2018-03-12 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_suggestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suggestion',
            new_name='suggestionM',
        ),
    ]
