# Generated by Django 2.0 on 2018-02-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180216_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
