# Generated by Django 2.0 on 2018-03-06 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_verify_pending'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='verify_pending',
            new_name='verified',
        ),
    ]
