# Generated by Django 2.0 on 2018-02-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
