# Generated by Django 2.0 on 2018-02-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tranrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranrecord',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.InvoiceRecord'),
        ),
    ]
