# Generated by Django 2.0 on 2018-02-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20180222_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsinvoice',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='accountsinvoice',
            name='name',
        ),
    ]
