# Generated by Django 2.0 on 2018-02-22 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20180222_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsinvoice',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
