# Generated by Django 2.0 on 2018-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_accounting_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranrecord',
            name='category',
            field=models.CharField(blank=True, default='sales', max_length=50),
        ),
    ]
