# Generated by Django 2.0 on 2018-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_remove_tranrecord_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranrecord',
            name='category',
            field=models.CharField(blank=True, default='Sales', max_length=50),
        ),
    ]
