# Generated by Django 2.0 on 2018-02-20 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2018, 2, 20)),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
