# Generated by Django 2.0 on 2018-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180220_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
